apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qdrantclusters.qdrant.io
spec:
  group: qdrant.io
  names:
    kind: QdrantCluster
    plural: qdrantclusters
    shortNames: []
    singular: qdrantcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              image:
                properties:
                  repository:
                    type: string
                  pullPolicy:
                    type: string
                  tag:
                    type: string
                type: object
              persistence:
                properties:
                  size:
                    type: string
                  storageClassName:
                    type: string
                type: object
              replicas:
                format: int32
                type: integer
              metrics:
                properties:
                  serviceMonitorEnabled:
                    type: boolean
                  grafana:
                    properties:
                      dashboardEnabled:
                        type: boolean
                      datasourceName:
                        type: string
                      instanceSelector:
                        properties:
                          matchExpressions:
                            items:
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                values:
                                  items:
                                    type: string
                                  type: array
                              type: object
                            type: array
                          matchLabels:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
                    type: object
                  interval:
                    type: string
                  scrapeTimeout:
                    type: string
                  honorLabels:
                    type: boolean
                type: object
              nodeSelector:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
              antiAffinity:
                type: boolean
              resources:
                properties:
                  claims:
                    items:
                      properties:
                        name:
                          type: string
                      type: object
                    type: array
                  limits:
                    additionalProperties:
                      properties:
                        format:
                          enum:
                          - decimalexponent
                          - binarysi
                          - decimalsi
                          type: string
                        value:
                          type: string
                      type: object
                    type: object
                  requests:
                    additionalProperties:
                      properties:
                        format:
                          enum:
                          - decimalexponent
                          - binarysi
                          - decimalsi
                          type: string
                        value:
                          type: string
                      type: object
                    type: object
                type: object
              podSecurityContext:
                properties:
                  fsGroup:
                    format: int64
                    type: integer
                  fsGroupChangePolicy:
                    type: string
                  runAsGroup:
                    format: int64
                    type: integer
                  runAsNonRoot:
                    type: boolean
                  runAsUser:
                    format: int64
                    type: integer
                  seLinuxOptions:
                    properties:
                      level:
                        type: string
                      role:
                        type: string
                      type:
                        type: string
                      user:
                        type: string
                    type: object
                  seccompProfile:
                    properties:
                      localhostProfile:
                        type: string
                      type:
                        type: string
                    type: object
                  supplementalGroups:
                    items:
                      format: int64
                      type: integer
                    type: array
                  sysctls:
                    items:
                      properties:
                        name:
                          type: string
                        value:
                          type: string
                      type: object
                    type: array
                  windowsOptions:
                    properties:
                      gmsaCredentialSpec:
                        type: string
                      gmsaCredentialSpecName:
                        type: string
                      hostProcess:
                        type: boolean
                      runAsUserName:
                        type: string
                    type: object
                type: object
              securityContext:
                properties:
                  allowPrivilegeEscalation:
                    type: boolean
                  capabilities:
                    properties:
                      add:
                        items:
                          type: string
                        type: array
                      drop:
                        items:
                          type: string
                        type: array
                    type: object
                  privileged:
                    type: boolean
                  procMount:
                    type: string
                  readOnlyRootFilesystem:
                    type: boolean
                  runAsGroup:
                    format: int64
                    type: integer
                  runAsNonRoot:
                    type: boolean
                  runAsUser:
                    format: int64
                    type: integer
                  seLinuxOptions:
                    properties:
                      level:
                        type: string
                      role:
                        type: string
                      type:
                        type: string
                      user:
                        type: string
                    type: object
                  seccompProfile:
                    properties:
                      localhostProfile:
                        type: string
                      type:
                        type: string
                    type: object
                  windowsOptions:
                    properties:
                      gmsaCredentialSpec:
                        type: string
                      gmsaCredentialSpecName:
                        type: string
                      hostProcess:
                        type: boolean
                      runAsUserName:
                        type: string
                    type: object
                type: object
              podAnnotations:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
              podLabels:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            type: object
          status:
            properties:
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}