apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qdrantclusters.qdrant.io
spec:
  group: qdrant.io
  names:
    kind: QdrantCluster
    plural: qdrantclusters
    shortNames: []
    singular: qdrantcluster
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              image:
                properties:
                  repository:
                    type: string
                  pullPolicy:
                    type: string
                  tag:
                    type: string
                type: object
              persistence:
                properties:
                  size:
                    type: string
                  storageClassName:
                    type: string
                type: object
              replicas:
                format: int32
                type: integer
              metrics:
                properties:
                  serviceMonitorEnabled:
                    type: boolean
                  grafana:
                    properties:
                      dashboardEnabled:
                        type: boolean
                      datasourceName:
                        type: string
                      instanceSelector:
                        properties:
                          matchExpressions:
                            items:
                              properties:
                                key:
                                  type: string
                                operator:
                                  type: string
                                values:
                                  items:
                                    type: string
                                  type: array
                              type: object
                            type: array
                          matchLabels:
                            additionalProperties:
                              type: string
                            type: object
                        type: object
                    type: object
                  interval:
                    type: string
                  scrapeTimeout:
                    type: string
                  honorLabels:
                    type: boolean
                type: object
              nodeSelector:
                items:
                  properties:
                    key:
                      type: string
                    value:
                      type: string
                  type: object
                type: array
            type: object
          status:
            properties:
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}