apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.example.neonkube.io
spec:
  group: example.neonkube.io
  names:
    kind: Example
    plural: examples
    shortNames: []
    singular: example
  scope: Namespaced
  versions:
  - additionalPrinterColumns: []
    name: v1alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              message:
                type: string
            type: object
          status:
            properties:
              message:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}