apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qdrant-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qdrant-operator
subjects:
- kind: ServiceAccount
  name: qdrant-operator
  namespace: '{{ .Release.Namespace }}'