apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: qdrant-operator
rules:
- apiGroups:
  - ""
  resourceNames:
  - qdrant-operator-webhook-tls
  resources:
  - secrets
  verbs:
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - '*'